//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroPhotoGallery.Common.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AstroPhotoGallery.Common.Resources.Admin.CategoryResources", typeof(CategoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new category.
        /// </summary>
        public static string btnCreateNewCategory {
            get {
                return ResourceManager.GetString("btnCreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find category by name:.
        /// </summary>
        public static string lblFindCategoryByName {
            get {
                return ResourceManager.GetString("lblFindCategoryByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category&apos;s name.
        /// </summary>
        public static string phCategoryName {
            get {
                return ResourceManager.GetString("phCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string titleActions {
            get {
                return ResourceManager.GetString("titleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin - create a category.
        /// </summary>
        public static string titleAdd {
            get {
                return ResourceManager.GetString("titleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string titleCategories {
            get {
                return ResourceManager.GetString("titleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin - delete category.
        /// </summary>
        public static string titleDelete {
            get {
                return ResourceManager.GetString("titleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin - edit category.
        /// </summary>
        public static string titleEdit {
            get {
                return ResourceManager.GetString("titleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin - categories.
        /// </summary>
        public static string titleIndex {
            get {
                return ResourceManager.GetString("titleIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string valueSearch {
            get {
                return ResourceManager.GetString("valueSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pictures in that category will be deleted too. This can take much time and resources, depending on their count..
        /// </summary>
        public static string warningDeleteMessage {
            get {
                return ResourceManager.GetString("warningDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the below category?.
        /// </summary>
        public static string warningDeleteQuestion {
            get {
                return ResourceManager.GetString("warningDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pictures in that category will be edited too. This can take much time and resources, depending on their count..
        /// </summary>
        public static string warningEditMessage {
            get {
                return ResourceManager.GetString("warningEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to edit the below category&apos;s name?.
        /// </summary>
        public static string warningEditQuestion {
            get {
                return ResourceManager.GetString("warningEditQuestion", resourceCulture);
            }
        }
    }
}
